### ISSUE TITLE
Can it get rid of unlocked bootloader warning?

### ISSUE THREAD

**Issue by mizzunet** [libxzr/vbmeta-disable-verification#1]
Does patching vbmeta for disabling verification removes bootloader unlocked warning?

Thanks

**Comment by libxzr** [comment]
No, it doesn't.
For removing unlock warning, you may need to flash specific abl image. Find more information in related forum.

**Comment by mizzunet** [comment]
Would you please add support for Snapdragon 730 on your KonaBess. That'd be wonderful. I could be the tester. Thanks you.

I have messaged in telegram a while back.
